### PR TITLE
new: various workflow optimizations

### PR DESCRIPTION
**Pull request by Wyvest**
## Description
This change should make workflows much faster.

## Checklist
- [x] I made a clear description of what was changed
- [x] I stated why these changes were necessary
- [x] I updated documentation or said what needs to be updated
- [x] I made sure these changes are backwards compatible
- [x] This pull request is for one feature/bug fix

### CODE REVIEW

**Review by EthanDevelops — DISMISSED** [review]
i literally made this but then diamond removed it lmao he thought the runner cached it or smth anyways LGTM

**Comment by DeDiamondPro** [comment]
This is not needed since setup java handles gradle cache

**Comment by Wyvest** [comment]
> This is not needed since setup java handles gradle cache

No it doesn't? Patcher caches gradle files and uses setup java too... Besides, it wouldn't be setup java's job to cache gradle's stuff...

**Comment by DeDiamondPro** [comment]
> > This is not needed since setup java handles gradle cache
> 
> 
> 
> No it doesn't? Patcher caches gradle files and uses setup java too... Besides, it wouldn't be setup java's job to cache gradle's stuff...

It 100% doesimage

**Comment by DeDiamondPro** [comment]
Read https://github.com/actions/setup-java#caching-gradle-dependencies

**Comment by DeDiamondPro** [comment]
And if that's not enough look at hud-improvements build, it had no cache hit took like 8 minutes. The locraw one did have a cache hit and only took 2 minutes 30

**Comment by Wyvest** [comment]
> > > This is not needed since setup java handles gradle cache
> > 
> > 
> > No it doesn't? Patcher caches gradle files and uses setup java too... Besides, it wouldn't be setup java's job to cache gradle's stuff...
> 
> It 100% doesimage

~~fuck~~

ok but it doesn't cache everything we need to cache so we should disable caching from setup java and then merge yes?

**Comment by EthanDevelops** [comment]
using the cache action also allows for a lot more customization like being able to clear the cache easily and choosing to cache other files (like loom cache, which is not included with gradle)

**Review by nxtdaydelivery — APPROVED** [review]

**Review by DeDiamondPro — APPROVED** [review]

**Review by nxtdaydelivery — APPROVED** [review]

**Pull request merged**
