### PR TITLE
various things

### LINKED ISSUE #160: OneKeyBind doesn't support mouse bindings

### PR DESCRIPTION
**Pull request by nxtdaydelivery**
## Description
- interface for nea

## Related Issue(s)
- fixes #160 

## Checklist
- [X] I made a clear description of what was changed
- [X] I stated why these changes were necessary
- [X] I updated documentation or said what needs to be updated
- [X] I made sure these changes are backwards compatible
- [X] This pull request is for one feature/bug fix

### CODE REVIEW

**Review by Wyvest — DISMISSED** [review]

**Review by TymanWasTaken — DISMISSED** [review]

**Review by xtrm-en — DISMISSED** [review]
:+1: Looks good

**Review by Wyvest — APPROVED** [review]

**Review by xtrm-en — DISMISSED** [review]
cool dump wy:b:est very cool

**Review by Wyvest — APPROVED** [review]
i forgor

**Review by xtrm-en — APPROVED** [review]
:+1:

**Review by TymanWasTaken — APPROVED** [review]

**Pull request merged**
