### PR TITLE
new: disable notifications

### PR DESCRIPTION
**Pull request by Wyvest**
add ability to disable notifications

debug notification page - might turn this into something that actually looks good later but we have bigger priorities rn

## Description
the debug page
Screenshot 2023-06-04 at 8 20 51 PM

## Checklist
- [x] I made a clear description of what was changed
- [x] I stated why these changes were necessary
- [x] I updated documentation or said what needs to be updated
- [x] I made sure these changes are backwards compatible
- [x] This pull request is for one feature/bug fix

### CODE REVIEW

**Comment by xtrm-en** [comment]
Looks very raw, the datetime is very cluttery, maybe just the time and a separator like `- Yesterday -` between days?

**Review by nxtdaydelivery — APPROVED** [review]
not on pc so haven't checked how it looks but code lgtm

**Comment by jani270** [comment]
# Suggestion for the empty space
image

**Comment by Wyvest** [comment]
> # Suggestion for the empty space
> image

so true

**Comment by CaledonianEH** [comment]
Does not pass QC - Do not merge.

**Comment by Wyvest** [comment]
> Does not pass QC - Do not merge.

💀💀💀

**Pull request closed without merging**
