### PR TITLE
Implement secondary licensing terms

### PR DESCRIPTION
**Pull request by Wyvest**
## Description
no anime

## Related Issue(s)
#69420

## Checklist
- [x] I made a clear description of what was changed
- [x] I stated why these changes were necessary
- [x] I updated documentation or said what needs to be updated
- [x] I made sure these changes are backwards compatible
- [x] This pull request is for one feature/bug fix

### CODE REVIEW

**Review by EthanDevelops — CHANGES_REQUESTED** [review]
pls no

**Review by nxtdaydelivery — APPROVED** [review]

**Comment by nxtdaydelivery** [comment]
hmm, on second thoughts I think this possibly breaking change might cause some issues with the codebase, but I will leave diamond to decide on these new terms. Some may perceive them as 'controversial'.

**Comment by Wyvest** [comment]
I don't think you guys understand this isn't actually legally binding lmfao

**Comment by DeDiamondPro** [comment]
Unfortunately the taco man stopped at the submarine which flew to a rainbow with water and then the taco man got lost in the water and couldn't deliver the review so this pr needs to be closed.

**Comment by EthanDevelops** [comment]
thank you

**Pull request closed without merging**
