### PR TITLE
Add ability to use image flags

### PR DESCRIPTION
**Pull request by DeDiamondPro**
## Description

Added the ability to give images and svgs custom flags like nearest neighbor scaling

## Related Issue(s)

Problems I'm having

## Checklist
- [X] I made a clear description of what was changed
- [X] I stated why these changes were necessary
- [X] I updated documentation or said what needs to be updated
- [X] I made sure these changes are backwards compatible
- [X] This pull request is for one feature/bug fix

### CODE REVIEW

**Review by Wyvest — APPROVED** [review]
Very Good Moon Tidez Approved

**Comment by DeDiamondPro** [comment]
> Very Good Moon Tidez Approved

No way highest level of approval

**Review by nxtdaydelivery — APPROVED** [review]
lgtm

**Comment by nxtdaydelivery** [comment]
Very Good Highly Appreciated

**Pull request merged**
