### PR TITLE
cubic bezier

### PR DESCRIPTION
**Pull request by DeDiamondPro**
## Description
Moon wanted cubic bezier animation, here it is

## Checklist
- [X] I made a clear description of what was changed
- [X] I stated why these changes were necessary
- [X] I updated documentation or said what needs to be updated
- [X] I made sure these changes are backwards compatible
- [X] This pull request is for one feature/bug fix

### CODE REVIEW

**Review by Wyvest — DISMISSED** [review]
looks fine to me, you should ask moon if adding license like that is the proper way though

**Review by nxtdaydelivery — APPROVED** [review]
looks good to me

**Review by nxtdaydelivery — APPROVED** [review]
yesyes

**Review by Wyvest — APPROVED** [review]
guay

**Review by nxtdaydelivery — APPROVED** [review]
publik statik voidless maintain stringlike args

**Review by MoonTidez — APPROVED** [review]
### Very epic licensing moment
Bottom text
Approved ✅

**Pull request merged**
