### PR TITLE
Notifs

### PR DESCRIPTION
**Pull request by DeDiamondPro**
## Description

- Made notification implementation
- Created "Icon" class for storing an svg or image
- Created ChainedAnimation for chaining animations
- Made DummyAnimation have some more functionality

Closes https://github.com/Polyfrost/OneConfig/issues/112

## Checklist
- [X] I made a clear description of what was changed
- [X] I stated why these changes were necessary
- [X] I updated documentation or said what needs to be updated
- [X] I made sure these changes are backwards compatible
- [X] This pull request is for one feature/bug fix

### CODE REVIEW

**Review by Wyvest — APPROVED** [review]

**Comment by DeDiamondPro** [comment]
@nxtdaydelivery please review but **DO NOT MERGE YET**

**Review by nxtdaydelivery — DISMISSED** [review]
lgtm

**Review by nxtdaydelivery — DISMISSED** [review]
lgtm

**Comment by pauliesnug** [comment]
o w o

**Review by Wyvest — APPROVED** [review]

**Review by nxtdaydelivery — APPROVED** [review]

**Pull request merged**
