### PR TITLE
additional config migrators

### PR DESCRIPTION
**Pull request by nxtdaydelivery**
## Description
JSON migrator for general JSON files
Vigilance migrator color support
forge .cfg file migration
(!) VigilanceName -> SerializedName

## Checklist
- [X] I made a clear description of what was changed
- [X] I stated why these changes were necessary
- [X] I updated documentation or said what needs to be updated
- [x] I made sure these changes are backwards compatible
- [X] This pull request is for one feature/bug fix

### CODE REVIEW

**Review by DeDiamondPro — CHANGES_REQUESTED** [review]
The migrator is way to complicated, it's meant for gson which only takes variable name into a count, you don't need delimiter things. Additionally serializedName is not a good name for the annotation.

**Comment by nxtdaydelivery** [comment]
> The migrator is way to complicated, it's meant for gson which only takes variable name into a count, you don't need delimiter things. Additionally serializedName is not a good name for the annotation.

ok I will remove those delimiter options, I thought name was the name in the @annotation. 
I will rename it to something else, but what should I call it?

**Comment by DeDiamondPro** [comment]
> > The migrator is way to complicated, it's meant for gson which only takes variable name into a count, you don't need delimiter things. Additionally serializedName is not a good name for the annotation.
> 
> 
> 
> ok I will remove those delimiter options, I thought name was the name in the @annotation. 
> 
> I will rename it to something else, but what should I call it?

OldName

**Review by DeDiamondPro — CHANGES_REQUESTED** [review]
Generate values and parse thing should not be defined in the interface since they aren't useful for public use and there are scenarios where they don't need an implementation

**Comment by DeDiamondPro** [comment]
Additionally the json migrator still doesn't work for gson and is way to complicated. Litterally field name and only field name is what you need, not option name, not category, nothing like that

**Comment by DeDiamondPro** [comment]
1. remove the stupid things that shouldn't be in an interface from the interface
2. get proper function names, "migrate" is not a good name for something that gets the value of a jsonPrimitive
3. give every migrator their own annotation so the things inside the annotation can be closer to what needed

**Review by DeDiamondPro — APPROVED** [review]

**Review by Wyvest — DISMISSED** [review]
can you actually use a cfg parser for the cfg migrator

**Review by Wyvest — APPROVED** [review]

**Pull request merged**
