### PR TITLE
fix: fix ci

### PR DESCRIPTION
**Pull request by Wyvest**
## Checklist
- [x] I made a clear description of what was changed
- [x] I stated why these changes were necessary
- [x] I updated documentation or said what needs to be updated
- [x] I made sure these changes are backwards compatible
- [x] This pull request is for one feature/bug fix

### CODE REVIEW

**Comment by Sainwa** [comment]
This is a very bad PR.

**Review by DeDiamondPro — APPROVED** [review]
If this doesn't work you're buying me lunch

**Review by nxtdaydelivery — APPROVED** [review]
ſ

**Comment by Wyvest** [comment]
> This is a very bad PR.

Ok

**Comment by Wyvest** [comment]
> If this doesn't work you're buying me lunch

NOOOOOO

**Comment by nxtdaydelivery** [comment]
*cries in null*

**Comment by Sainwa** [comment]
Kidding love u wyvest bestie

**Comment by EthanDevelops** [comment]
omg hi bff

**Pull request merged**
