### PR TITLE
add gametypes for classic games

### PR DESCRIPTION
**Pull request by MicrocontrollersDev**
## Description
add gametypes for classic games. needs API dump

## Related Issue(s)
NA

## Checklist
- [x] I made a clear description of what was changed
- [x] I stated why these changes were necessary
- [x] I updated documentation or said what needs to be updated
- [x] I made sure these changes are backwards compatible
- [x] This pull request is for one feature/bug fix

### CODE REVIEW

**Comment by MicrocontrollersDev** [comment]
also would it be fine to rename WOOL_GAMES to WOOL_WARS? similar to QUAKECRAFT -> QUAKE and WALLS3 -> MEGA_WALLS?

**Review by xtrm-en — DISMISSED** [review]
lgtm

**Comment by MicrocontrollersDev** [comment]
man

**Review by Wyvest — APPROVED** [review]

**Review by xtrm-en — DISMISSED** [review]
lgtm x2

**Comment by xtrm-en** [comment]
ok nvm u didnt apidump

**Review by xtrm-en — APPROVED** [review]
lgtm

**Review by Wyvest — APPROVED** [review]

**Review by nxtdaydelivery — APPROVED** [review]
good looks to me

**Pull request merged**
