### PR TITLE
add dropper locraw

### PR DESCRIPTION
**Pull request by MicrocontrollersDev**
## Description

adds dropper locraw took me a long time to do pls merge

## Related Issue(s)

none

## Checklist
- [x] I made a clear description of what was changed (doesn't get much clearer than this)
- [x] I stated why these changes were necessary
- [x] I updated documentation or said what needs to be updated
- [x] I made sure these changes are backwards compatible
- [x] This pull request is for one feature/bug fix

### CODE REVIEW

**Review by Wyvest — APPROVED** [review]
10/10 best pr

**Review by Wyvest — APPROVED** [review]
11/10

**Comment by MicrocontrollersDev** [comment]
man cant believe i actually messed it up actually shameful

**Comment by EthanDevelops** [comment]
best pr

**Review by nxtdaydelivery — APPROVED** [review]
its good, can we avoid mono PRs though, 2 lines is MASSIVE in the future could you split into multiple? thanks

**Comment by MicrocontrollersDev** [comment]
yes sir sorry sir wont happen again sir

**Pull request merged**
