### PR TITLE
Help subcommand impovments

### PR DESCRIPTION
**Pull request by pinkulu**
Improved the default "help" SubCommand
## Description

The default help SubCommand looked awful, so i changed how the command looks in general, i also added the "color" to `@Command` and `@SubCommand` which takes in ChatColor.
if the color field is not provided in `@Command`, the default color will be GOLD, if the color field is not provided in `@SubCommand`. the default color will be the color of `@Command`

im making a PR to hud-improvments as that was the branch i used to build it on, wasnt sure what other one to use

Before:
unknown

After:
unknown

With Color applied(just an example, i didn't do this to the OneConfig command):
unknown

## Checklist
- [x] I made a clear description of what was changed
- [x] I stated why these changes were necessary
- [ ] I updated documentation or said what needs to be updated
- [x] I made sure these changes are backwards compatible
- [x] This pull request is for one feature/bug fix

### CODE REVIEW

**Comment by pinkulu** [comment]
image

image

sub-sub commands can have their own colors or the subcommands(parents) color
image

image

code used for sub commands
image

**Comment by nxtdaydelivery** [comment]
thanks, if you add a space on the sub commands that would be very nice :)

**Comment by pinkulu** [comment]
thank you for editing 4 times becosue the first 3 i had no idea what you wanted from me

**Comment by koxx12-dev-is-bad** [comment]
i love becosue

**Comment by pinkulu** [comment]
@nxtdaydelivery you mean like this 
image

**Comment by Mqisty** [comment]
why that color tho

**Comment by pinkulu** [comment]
the color can be changed, using `@Command(color=ChatColor` and `@SubCommand(color=ChatColor)`, one of the things i added, the gold is just the default color becouse it was default so who cares

**Review by nxtdaydelivery — APPROVED** [review]
looks great now!

**Review by DeDiamondPro — APPROVED** [review]
Will be merged in a bit

**Pull request merged**
