### PR TITLE
fix: fix locraw cancelling all locraw messages

### PR DESCRIPTION
**Pull request by Wyvest**
## Description
This fixes locraw messages cancelling even if the user sent it themselves.

## Related Issue(s)
n/a

## Checklist
- [x] I made a clear description of what was changed
- [x] I stated why these changes were necessary
- [x] I updated documentation or said what needs to be updated
- [x] I made sure these changes are backwards compatible
- [x] This pull request is for one feature/bug fix

### CODE REVIEW

**Review by DeDiamondPro — CHANGES_REQUESTED** [review]
Just use the sentCommand variable directly and (very important) actually set it to false after cancelling one message since this is still going to cancel every locraw message after the command got sent once

**Review by DeDiamondPro — APPROVED** [review]

**Comment by Wyvest** [comment]
@Scherso you may want to make the same changes to Seraph, please let me know if you want me to make a PR for you in Seraph.

**Review by nxtdaydelivery — APPROVED** [review]
lgtm

**Comment by Scherso** [comment]
thanks for letting me skid ur code

**Pull request merged**
