### PR TITLE
Added getKeyBinds in OneKeybind and Documentation for OneKeybind

### PR DESCRIPTION
**Pull request by ForBai**
## Description
Added OneKeybind#getKeyBinds so you could get the set keys and use them for possibly using custom set Keybindings in GUIs/UIs.

## Related Issue(s)
None

## Checklist
- [X] I made a clear description of what was changed
- [X] I stated why these changes were necessary
- [X] I updated documentation or said what needs to be updated
- [X] I made sure these changes are backwards compatible
- [X] This pull request is for one feature/bug fix

### CODE REVIEW

**Comment by DeDiamondPro** [comment]
When you're done please run the `apiDump` gradle task

**Review by nxtdaydelivery — APPROVED** [review]
lgtm

**Review by DeDiamondPro — APPROVED** [review]
Sorry for the delay, this will be merged after some of our licensing changes have been done

**Comment by MoonTidez** [comment]
Hi! Thanks for your contribution. Really sorry for the delay. We have been looking at it for a while now, but we haven't merged it yet because of ongoing license changes. Since you submitted the pull request before we changed our license (see https://github.com/Polyfrost/OneConfig/pull/85), your contribution may technically fall under the LGPL only (and not under the Additional Terms we added recently). Although I would consider your contribution non-copyrightable (since it may not be considered 'creative work'), I still want to keep things transparent. I would advise you to read pull request #85 if you are interested. To accept your contribution, we require you to send the following text (below), just to be in the green legally. If you just want to get this contribution merged as fast as possible, you can skip reading pull request #85. If you want to dig deep, you can visit that PR. You are free to accept or reject this agreement request. However, we likely won't accept your contribution unless you agree to the following (as a comment to this pull request):

> I license past and future contributions under version 3 of the LGPL AND under the Additional Terms Applicable to OneConfig as published by Polyfrost, version 1.0 of the Additional Terms or (at the option of licensees) any later version.

Thank you for reading.

**Comment by nxtdaydelivery** [comment]
@ForBai

**Comment by MoonTidez** [comment]
The pull request that you made is licensed under the LGPL. However, it is **not** licensed under the Additional Terms Applicable to OneConfig. You sending that line of text will allow us to use your contribution under the new licensing (which includes the LGPL **and** the Additional Terms Applicable to OneConfig, not just the LGPL). 

Again, if you want to see the exact details of these Additional Terms, you can visit the linked pull request.

**Comment by MoonTidez** [comment]
@ForBai one last thing I forgot to ask for: do you have a public email address to add to the file header, marking you as a co-author? If you do not feel comfortable sharing an email address (that isn't a no-reply email), please let us know. Adding an email address is not a **requirement**; it is just recommended/optional. Your name will still show up as a co-author of the appropriate files.

**Pull request merged**
