### PR TITLE
Misc UI tweaks

### PR DESCRIPTION
**Pull request by Wyvest**
## Description
- Reduces button radius
- Fixes a potential NPE with color selector
- Removes color hex / alpha fields
- Makes color selector exit when page is closed
- Reduces slider thickness
- Adds icon to text input
- Reduces scroll bar width
- Reduces text input border
- Removes text input drop shadow
- Reduces text input font size

## Checklist
- [x] I made a clear description of what was changed
- [x] I stated why these changes were necessary
- [x] I updated documentation or said what needs to be updated
- [x] I made sure these changes are backwards compatible
- [x] This pull request is for one feature/bug fix

### CODE REVIEW

**Comment by pauliesnug** [comment]
looks gay to me

**Review by pauliesnug — DISMISSED** [review]

**Review by xtrm-en — DISMISSED** [review]
lgtm

**Comment by CaledonianEH** [comment]
Passes QC

**Review by CaledonianEH — APPROVED** [review]

**Review by xtrm-en — APPROVED** [review]
lgtm, the sequel

**Pull request merged**
